services:
    php:
        image: thecodingmachine/php:8.3-v4-fpm-node14
        working_dir: /var/www/symfony
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${SYMFONY_LOGS_PATH}:/var/www/symfony/var/logs
        mem_reservation: 4g
        environment:
            PHP_EXTENSION_IMAGICK: 1
            PHP_EXTENSION_XDEBUG: 1
            PHP_INI_MEMORY_LIMIT: 4g
            PHP_INI_MAX_EXECUTION_TIME: 3000
        restart: "no"

