name: Run tests

on: [push]

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}
        
        strategy:
            matrix:
                php: [7,1, 5.6]
                dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest, windows-latest]
        
        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v1
            
            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extension-csv: json fileinfo curl
                    coverage: none
            
            -   name: Install dependencies
                run: composer install --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
            
            -   name: Execute tests
                run: vendor/bin/phpunit
